In [61]:
import numpy as np

# For gray-scale image convoluting
from PIL import Image

In [63]:
# For ilustrating an array with values from 0 to 12

def illumination(array):
    color_array = np.empty([array.shape[0], array.shape[1]])
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            if array[i][j] == 0:
                print(" . ", end="")
            elif array[i][j] == 1:
                print(" . ", end="")
            elif array[i][j] == 3:
                print(" , ", end="")
            elif array[i][j] == 2:
                print(" ~ ", end="")
            elif array[i][j] == 4:
                print(" : ", end="")
            elif array[i][j] == 5:
                print(" ; ", end="")
            elif array[i][j] == 6:
                print(" = ", end="")
            elif array[i][j] == 7:
                print(" ! ", end="")
            elif array[i][j] == 8:
                print(" * ", end="")
            elif array[i][j] == 9:
                print(" # ", end="")
            elif array[i][j] == 10:
                print(" $ ", end="")
            elif array[i][j] == 11:
                print(" @ ", end="")

        print()
    # return color_array

In [200]:
#

# np.random.seed(35)
# feed_in_channel = np.random.randint(12, size=(50, 50))


frame = Image.open("test.png").convert('L')

feed_in_channel = np.asarray(frame)

print(feed_in_channel.shape)

# print(illumination(feed_in_channel))

(50, 50)


In [215]:
kernel_channel = np.array(
    [
        [1, 1, 2, 2, 1, 1],
        [1, 1, 2, 2, 1, 1],
        [1, 2, 6, 6, 2, 1],
        [1, 2, 6, 6, 2, 1],
        [1, 1, 2, 2, 1, 1],
        [1, 1, 2, 2, 1, 1]        

    ]
)
kernel_channel = np.random.randint(100, size=(20,20))

kernel_channel
# kernel_channel*feed_in_channel[:4,:4]
# sum(kernel_channel * feed_in_channel[:4, :4])

array([[50, 57, 11, 94, 86, 79, 46, 25, 54, 58,  8, 90, 15, 89, 56, 54,
        98, 32, 52, 35],
       [44, 41, 20, 38, 29, 60, 76, 34, 93, 11, 64, 84, 45, 28, 98,  8,
        88, 98, 49,  0],
       [75, 95, 24, 45,  0, 82,  5, 21, 55, 73, 44, 99, 76, 85, 92, 84,
        59, 73, 49, 91],
       [16, 73, 23, 72, 63, 30, 43, 79, 95, 50, 72, 12,  2, 71, 64, 38,
        22, 41, 70, 87],
       [ 2, 84, 56, 18, 61, 18,  4, 31, 30, 80, 59, 95, 78, 70, 86, 13,
        13, 47, 63, 42],
       [71,  7,  1, 75, 24, 50, 97, 87, 67, 83, 20,  4,  0, 76, 28, 12,
        79, 54, 61, 98],
       [49, 62, 27, 92, 82, 46, 31, 46, 94,  9, 95, 32, 40, 75, 42, 27,
        52, 40,  9, 55],
       [63, 95, 34, 59, 10,  8, 88, 17, 62, 40, 61, 50, 26, 85, 83, 51,
         6, 45, 18, 73],
       [62, 37, 55, 51,  7,  7,  4, 95,  9, 15, 52, 94, 53, 67,  7, 73,
        74, 18, 81, 86],
       [76, 24,  4, 86, 16,  7, 66, 79, 35, 45, 58, 34, 97, 73, 14,  8,
        51, 33, 74, 40],
       [16, 32, 20,  0, 10, 38

In [216]:
def quick_dot(array1, array2):
    array1 = array1 * array2
    sum1 = sum(array1)
    sum2 = 0
    for i in sum1:
        sum2 += i
    return sum2


In [217]:
def convolution(feed_in, kernel):
    stepsX = feed_in.shape[0] - kernel.shape[0] + 1
    stepsY = feed_in.shape[1] - kernel.shape[1] + 1
    print(stepsX, stepsY)
    new = np.zeros([stepsX, stepsY], dtype=int)
    count = 0
    for i in range(stepsX):
        for j in range(stepsY):
            # print(i,j,end=" ")
            # croping the feed array so the dot product will work
            new_input = feed_in[i:kernel.shape[0] + i, j:kernel.shape[1] + j]
            new[i][j] = quick_dot(new_input, kernel)

            print(new_input)
            # print(new_input.shape)
            # count+=1
            # print(count)
    return new

In [218]:
output_channel = convolution(feed_in_channel, kernel_channel)

31 31
[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [255 255 255 255 255 255 183  32   0   0   0   0  32 159 255 255 255 255
  255 255]
 [255 255 255 255 255 255  32   0   0   0   0   0   0   0   0   0   0  32
  159 255]
 [255 255 255 255 255 255 135   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [255 255 255 255 255 255 255 255 255 255 255 135   0   0   0   0   0   0
    0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 135   0
    0   0]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
  255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 2

In [219]:
# maxi= np.amax(output_channel)
mini = np.amin(output_channel)

output_channel
# print(np.cov(feed_in_channel, kernel_channel))

array([[4581444, 4544263, 4489861, 4439645, 4399699, 4386762, 4377672,
        4369632, 4363297, 4367196, 4367922, 4344542, 4316712, 4265327,
        4187921, 4096331, 4011037, 3949440, 3874849, 3815202, 3783496,
        3783010, 3878647, 3888632, 3874201, 3892936, 3864424, 3939341,
        4032887, 4024651, 4070995],
       [4563407, 4565721, 4536298, 4494466, 4464253, 4414959, 4357708,
        4328321, 4323976, 4321135, 4319990, 4310913, 4263317, 4205006,
        4135153, 4035305, 3979732, 3882635, 3819827, 3783258, 3737727,
        3773288, 3836258, 3814189, 3808738, 3824181, 3820841, 3919944,
        3985719, 3995136, 4087086],
       [4482680, 4432889, 4416755, 4389060, 4376637, 4366500, 4355979,
        4357166, 4359390, 4351261, 4307964, 4257985, 4202085, 4130052,
        4053832, 3964838, 3890351, 3808784, 3756300, 3730503, 3723273,
        3756682, 3774872, 3758771, 3765690, 3765898, 3818990, 3899580,
        3918766, 3962567, 4059142],
       [4503248, 4483207, 4450328, 43991

In [220]:
output_channel_prepared = output_channel
maxi = np.amax(output_channel_prepared)
# output_channel_prepared,maxi

output_channel_prepared = 255 * ((output_channel - mini) / (maxi - mini))
output_channel_prepared = np.round(output_channel_prepared)
output_channel_prepared


array([[176., 171., 163., 156., 151., 149., 148., 146., 145., 146., 146.,
        143., 139., 132., 121., 108.,  95.,  87.,  76.,  68.,  63.,  63.,
         77.,  78.,  76.,  79.,  75.,  85.,  99.,  97., 104.],
       [174., 174., 170., 164., 160., 153., 145., 140., 140., 139., 139.,
        138., 131., 123., 113.,  99.,  91.,  77.,  68.,  63.,  57.,  62.,
         71.,  68.,  67.,  69.,  68.,  83.,  92.,  93., 106.],
       [162., 155., 153., 149., 147., 146., 144., 145., 145., 144., 138.,
        131., 123., 112., 102.,  89.,  78.,  67.,  59.,  56.,  55.,  59.,
         62.,  60.,  61.,  61.,  68.,  80.,  82.,  89., 102.],
       [165., 162., 158., 151., 144., 137., 130., 127., 126., 126., 123.,
        118., 110., 101.,  90.,  78.,  62.,  51.,  43.,  37.,  41.,  41.,
         40.,  44.,  43.,  51.,  63.,  71.,  77.,  86., 101.],
       [174., 167., 161., 154., 151., 150., 146., 142., 139., 132., 122.,
        110., 100.,  85.,  78.,  65.,  52.,  43.,  33.,  32.,  30.,  26.,
        

In [221]:
image_done = Image.fromarray(output_channel_prepared)
image_done.show()

In [ ]:
illumination(output_channel_prepared)


In [81]:
illumination(feed_in_channel)
































































































































































 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 













































 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 








































 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 























 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  .  . 
 .  